name: wpfreelance
favicon: null
layout_spectrum: 0.6166070736944675
typography_spectrum: 0.1801959713920951
title: 'WPFreelance - a Web Design and Development Agency focused on WordPress and Design '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9f4f8'
    - '#87c0d7'
    - '#337397'
    - '#f1b09e'
    - '#639ab6'
  brandStrength: 1
  lightness: 0.9816217212937772
  saturation: 0.4891269060317427
  rhythmicContrast: 0.11236686655320227
purpose: []
